# Generated by Django 3.2.5 on 2021-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default='PrivatBank', editable=False, max_length=24, unique=True),
            preserve_default=False,
        ),
    ]
