# Generated by Django 3.2.5 on 2021-09-21 21:36

from currency import model_choises as mch

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    for rate in Rate.objects.all().only('type'):
        if 'usd' in rate.type.lower():
            rate.type = mch.TYPE_USD
        elif 'eur' in rate.type.lower():
            rate.type = mch.TYPE_EUR
        elif 'rub' in rate.type.lower():
            rate.type = mch.TYPE_RUB
        else:
            rate.type = mch.TYPE_USD

        rate.save(update_fields=('type', ))


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210921_0501'),
    ]

    operations = [
    ]
