# Generated by Django 3.2.5 on 2021-11-22 12:39

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(default=None, null=True, upload_to=currency.models.upload_logo),
        ),
    ]
