# Generated by Django 3.2.5 on 2021-11-22 12:50

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_source_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.upload_logo),
        ),
    ]
